### PR TITLE
feat: add ProfileCallback for per-invocation profiling

### LINKED ISSUE #90: Add a built-in profiling callback for per-invocation timing analysis
## Problem

When investigating where time is spent during an LLMeter run, users currently need to write custom ad-hoc callbacks (as seen in dev notebooks) to capture per-request phase timings. There is no built-in way to:

1. **Break down request time into server-side phases** — specifically separating prefill (TTFT) from generation (decode), and distinguishing server time from client-side runner overhead.

2. **Capture per-invocation metadata** alongside timing — cache hit status, reasoning token counts, retry counts, and throughput metrics — in a structured format suitable for analysis.

3. **Persist profiling data** to disk for post-hoc analysis without needing the live callback or endpoint.

4. **Visualize profiling results** with ready-made plots (phase breakdown, request timeline/concurrency, throughput over time, TPOT distribution, etc.).

## Expected Behavior

A built-in `ProfileCallback` that:
- Hooks into the existing callback lifecycle (`before_invoke` / `after_invoke` / `after_run`)
- Captures detailed per-invocation profiles (timing phases, token counts, cache info, retries)
- Produces an aggregated report with time accounting and percentile statistics
- Saves structured data (JSON + JSONL) alongside run results
- Contributes summary stats to `result.stats` for programmatic access
- Pairs with plotting utilities for common profiling visualizations

## Use Case

Understanding where wall-clock time goes in a benchmark run — especially distinguishing server-side prefill and decode from client-side overhead — and identifying patterns like cache hit impact on TTFT, throughput degradation over time, or concurrency effects.

### PR DESCRIPTION
**Pull request by acere**
Closes #90

## Summary

Adds a built-in `ProfileCallback` that captures per-invocation timing data during a Runner run and produces a structured profiling report.

### New: `llmeter/callbacks/profiling.py`
- `InvocationProfile` dataclass — per-request record with timing phases, token counts, cache info, retries
- `ProfileReport` dataclass — aggregated summary with time accounting, cache hit rate, retry stats, percentile statistics
- `ProfileCallback` — lifecycle hooks that collect data and generate the report in `after_run`
- Saves `profile_report.json` + `profile_invocations.jsonl` alongside run results

### New: `llmeter/plotting/profiling.py`
- `plot_phase_breakdown` — stacked bar (TTFT vs generation per request)
- `plot_request_timeline` — Gantt-style concurrency view
- `plot_throughput_over_time` — tok/s scatter with rolling average
- `plot_time_accounting` — pie chart (server prefill vs decode vs client overhead)
- `plot_tpot_distribution` — TPOT histogram
- `plot_ttft_vs_input_tokens` — scatter with cache hits highlighted
- `plot_profile_summary` — 2×2 multi-panel dashboard

### Supporting changes
- `llmeter/callbacks/__init__.py` — exports `ProfileCallback`
- `llmeter/plotting/__init__.py` — exports profiling plot functions
- `mkdocs.yml` — nav entries for new API reference pages
- `docs/reference/callbacks/profiling.md` + `docs/reference/plotting/profiling.md`
- `examples/Profiling.ipynb` — full walkthrough notebook

### Tests
- `tests/unit/callbacks/test_profiling.py` — 29 tests covering serialization, lifecycle, report computation, stats contribution, file saving, and edge cases

## Terminology

Clear server/client separation in naming:
- **TTFT** = server prefill + network round-trip
- **Generation time** = server-side decode (TTLT − TTFT)
- **Runner overhead** = client-side (queue, token counting, callbacks)

## Testing

```bash
uv run pytest tests/unit/callbacks/test_profiling.py -v  # 29 passed
uv run ruff check llmeter/callbacks/profiling.py llmeter/plotting/profiling.py
```

### CODE REVIEW

**Comment by athewsey** [comment]
(Note, seems like this PR depends on plotting.defaults introduced in #89)

Just seen a weird intermittent error while testing the example notebook here... Requests failing with:

```
Endpoint invocation failed: 'dict' object has no attribute 'id'
Traceback (most recent call last):
  File "{...}/llmeter/llmeter/endpoints/base.py", line 259, in wrapper
    self.process_raw_response(raw_response, start_t, response)
  File "{...}/llmeter/llmeter/endpoints/openai_response.py", line 281, in process_raw_response
    response.id = event.response.id
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'id'
```

The same happens with `google.gemma-4-31b` on the same new `/openai/v1` endpoint, but interestingly **not** with `openai.gpt-oss-120b` on the old `/v1` endpoint. Claude couldn't figure yet what path through the OpenAI Python SDK could possibly be allowing this object to pass through un-parsed.

Will come back to it later
